security:
    providers:
        fos_userbundle:
#            id: fos_user.user_manager
            id: fos_user.user_provider.username 
        
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        
    firewalls:
        main:
            pattern: ^/
            logout: true
            anonymous: true
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                use_forward: true
                check_path: /login_check
                post_only: true
                always_use_default_target_path: false
                default_target_path: /
                target_path_parameter: _target_path
                use_referer: false
                failure_path: null
                failure_forward: false
                username_parameter: _username
                password_parameter: _password
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /admin, role: ROLE_ADMIN }
        - { path: ^/ksiazka/admin, role: ROLE_ADMIN }
        - { path: ^/zarzadca/, role: ROLE_ADMIN }
        - { path: ^/kategoria/admin, role: ROLE_ADMIN }
        - { path: ^/panel/szczegoly-zamowienia/, role: ROLE_USER }
#        - { path: ^/, role: ROLE_ADMIN }
        
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN