# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

#    PONIŻSZE DOTYCZY NADPISANEGO FORMULARZA REJESTRACJI, Z KTÓREGO ZREZYGNOWAŁEM    
     user.registration.form.type:
         class: UserBundle\Form\Type\RegistrationFormType
         tags:
             - { name: form.type, alias: user_registration }
             



