<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ZamowienieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZamowienieRepository extends EntityRepository
{
    public function findAllOrderedByY($sortArr,$OrderBy)
    {
        switch ($OrderBy) {
            case 'datazlozenia':
                $sort=$sortArr['Data'];
                break;
            case 'idklient':
                $sort=$sortArr['Klient'];
                break;
            case 'idstatus':
                $sort=$sortArr['Status'];
                break;
            default:
                $sort=$sortArr['Numer'];
        }
       
//        $qb->select('z')
//            ->from('AppBundle:Zamowienie', 'z')
////            ->where('u.id = :identifier')
//            ->orderBy('z.'.$OrderBy, $sort);
////            ->setParameter('identifier', 100);
        return $this->getEntityManager()
            ->createQuery(
//                    $qb
                'SELECT z FROM AppBundle:Zamowienie z ORDER BY z.'.$OrderBy.' '.$sort.''
            )
            ->getResult();
    }
    
    
    public function findByXOrderedByY($query,$sortArr,$OrderBy='idzamowienie')
    {
//        echo '<pre>',print_r($EntFldName),'</pre>'; //'status' a ma być idstatus
//        echo '<pre>',print_r($Identifier),'</pre>'; //OBJECT, ale 'wyslane;
//        echo '<pre>',print_r($sortArr),'</pre>';    //Array ( [Status] => null [Klient] => null [Numer] => null [Data] => ASC )
//        echo '<pre>',print_r($OrderBy),'</pre>';    //'idzamowienie'
        switch ($OrderBy) {
            case 'datazlozenia':
                $sort=$sortArr['Data'];
                break;
            case 'idklient':
                $sort=$sortArr['Klient'];
                break;
            case 'idstatus':
                $sort=$sortArr['Status'];
                break;
            default:
                $sort=$sortArr['Numer'];
        }
        
        return $this->getEntityManager()
            ->createQuery(
                'SELECT z 
                FROM AppBundle:Zamowienie z 
                WHERE z.'.$query .' 
                ORDER BY z.'.$OrderBy.' '.$sort.''
            )
//                ->setParameters(array( 'sort'=>$sort,'orderby'=>$OrderBy))
            ->getResult();
    }
}
